// Generated by CoffeeScript 1.10.0
(function() {
  var CLIENT, FS_BASE_URL, VERSION, getLocation, getVenues;

  $(document).foundation();

  $(document).ready(function() {
    return getLocation((function(_this) {
      return function(pos) {
        return getVenues(pos).then(function(venues) {
          return console.log(venues);
        });
      };
    })(this));
  });

  FS_BASE_URL = 'https://api.foursquare.com/v2/venues/search';

  CLIENT = {
    ID: 'ALACXFWGU1XEMQICBNALEBIIUIADEBNX1SJI4NDKLTA3Y5YA',
    SECRET: '2ILT1RCBIKENEDYFBCKP5ZFX1E5Q3NJBJTS4L5SBJEV2TJ5Q'
  };

  VERSION = '20160329';

  getLocation = function(cb) {
    if (navigator.geolocation) {
      return navigator.geolocation.getCurrentPosition(cb);
    } else {
      return alert('Location not supported. Daymn...');
    }
  };

  getVenues = function(pos) {
    var headers, url;
    headers = new Headers({});
    url = FS_BASE_URL + ("?ll=" + pos.coords.latitude + "," + pos.coords.longitude + "&client_id=" + CLIENT.ID + "&client_secret=" + CLIENT.SECRET + "&v=" + VERSION);
    return fetch(url, headers).then(function(resp) {
      return resp.json();
    }).then(function(data) {
      return data.response.venues;
    })["catch"](function(error) {
      return console.log('error', error);
    });
  };

}).call(this);
